#!/bin/bash
# Intended for OpenMandriva (or Fedora) based distros, and for new installs.
# This script may not work well on gaming based distros since those come with needed libraries installed.
# THIS SCRIPT IS A WORK IN PROGRESS, USE AT YOUR OWN RISK!

# Ensure curl is installed
sudo dnf install -y curl

# Install Brave
curl -fsS https://dl.brave.com/install.sh | sh

#Install Floorp (Flatpak version)
flatpak install flathub one.ablaze.floorp -y

# Gaming Stuff + Lutris
sudo dnf install -y lutris
sudo dnf install -y mangohud
sudo dnf install -y gamescope
sudo dnf install -y wine

# Utilities
sudo dnf install -y hardinfo2
sudo dnf install -y lm-sensors psensor
sudo dnf install -y neofetch
sudo dnf install -y htop
sudo dnf install -y gparted
sudo dnf install -y git

# Upgrade All Installed Packages
sudo dnf distro-sync -y

sudo dnf clean all
