#!/bin/bash
# Intended for OpenMandriva (or Fedora) based distros, and for new installs.
# This script may not work well on gaming based distros since those come with needed libraries installed.
# THIS SCRIPT IS A WORK IN PROGRESS, USE AT YOUR OWN RISK!

# Ensure Curl is installed
sudo dnf -y install curl

# Install Brave
#curl -fsS https://dl.brave.com/install.sh | sh
#or
sudo dnf install dnf-plugins-core
sudo dnf config-manager addrepo --from-repofile=https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
sudo dnf -y install brave-browser

# Install Floorp (Flatpak version)
flatpak install flathub one.ablaze.floorp -y

# Gaming Stuff + Lutris
sudo dnf -y install lutris
sudo dnf -y install mangohud
sudo dnf -y install gamescope
sudo dnf -y install wine

# Utilities
sudo dnf -y install hardinfo2
sudo dnf -y install lm-sensors psensor
sudo dnf -y install neofetch
sudo dnf -y install htop
sudo dnf -y install gparted
sudo dnf -y install git

# Upgrade All Installed Packages
sudo dnf -y distro-sync

# Other
sudo dnf -y install brave-browser

# Clean Up
sudo dnf -y clean all
