#!/bin/bash
# Make sure curl is installed
sudo dnf install -y curl

# Install Brave
curl -fsS https://dl.brave.com/install.sh | sh

# Gaming Stuff + Lutris
sudo dnf install -y lutris
sudo dnf install -y mangohud
sudo dnf install -y gamescope
# sudo dnf install -y libvulkan1
# sudo dnf install -y libvulkan1:i386

# Utilities
sudo dnf install -y hardinfo
sudo dnf install -y lm-sensors psensor
sudo dnf install -y neofetch
sudo dnf install -y htop
sudo dnf install -y gparted
sudo dnf install -y git

# Upgrade All Installed Packages
sudo dnf distro-sync -y
